name: CS

on:
    pull_request:

permissions:
    contents: read

jobs:
    call-inspector-bot:
        name: InspectorBot
        uses: rollerscapes/inspector-bot/.github/workflows/inspector-bot.yml@main
        with:
            package: RollerworksUriEncoder
            check_license: true

